module.exports = {
  rooms: [
    {
      id: 0,
      westWall: true,
      northWall: true,
      eastWall: true,
      southWall: true,
    },
    {
      id: 1,
      westWall: true,
      northWall: false,
      eastWall: true,
      southWall: true,
    },
    {
      id: 2,
      westWall: true,
      northWall: true,
      eastWall: true,
      southWall: true,
    },
    {
      id: 3,
      westWall: true,
      northWall: true,
      eastWall: true,
      southWall: true,
    },
    {
      id: 4,
      westWall: true,
      northWall: true,
      eastWall: false,
      southWall: true,
    },
    {
      id: 5,
      westWall: false,
      northWall: false,
      eastWall: false,
      southWall: false,
    },
    {
      id: 6,
      westWall: false,
      northWall: true,
      eastWall: false,
      southWall: true,
    },
    {
      id: 7,
      westWall: false,
      northWall: false,
      eastWall: true,
      southWall: true,
    },
    {
      id: 8,
      westWall: true,
      northWall: true,
      eastWall: true,
      southWall: true,
    },
    {
      id: 9,
      westWall: true,
      northWall: false,
      eastWall: true,
      southWall: false,
    },
    {
      id: 10,
      westWall: true,
      northWall: true,
      eastWall: true,
      southWall: true,
    },
    {
      id: 11,
      westWall: true,
      northWall: false,
      eastWall: true,
      southWall: false,
    },
    {
      id: 12,
      westWall: true,
      northWall: true,
      eastWall: true,
      southWall: true,
    },
    {
      id: 13,
      westWall: true,
      northWall: true,
      eastWall: false,
      southWall: false,
    },
    {
      id: 14,
      westWall: false,
      northWall: true,
      eastWall: false,
      southWall: true,
    },
    {
      id: 15,
      westWall: false,
      northWall: true,
      eastWall: true,
      southWall: false,
    }
  ]
}
